---
baseurl: https://www.edgarding.cn
title: EdgarDing Blog
theme: hugo-theme-cleanwhite
languageCode: en-us
disqusShortname: "edgarding"
googleAnalytics: "G-QB764C3NYN"

preserveTaxonomyNames: true
paginate: 10
hasCJKLanguage: true
taxonomies:
  category: categories
  tag: tags
outputs:
  home:
    - HTML
    - RSS
    - Algolia

params:
  header_image: img/home-bg-main.jpg
  SEOTitle: EdgarDing 的博客 | One day One day
  description: 一天又一天
  keyword: Edgarding, 博客, 个人网站, 互联网, Web, 云原生, PaaS, Kubernetes, 云平台
  slogan: You Only Live Once.
  image_404: img/404-bg.jpg
  title_404: 你来到了没有知识的荒原 :(
  leancloud_app_id: ""
  leancloud_app_key: ""
  sidebar_about_description: I hope the day comes easy and the moments pass slow, And each road leads you where you want to go.
  sidebar_avatar: img/edgarding.jpeg
  featured_tags: true
  featured_condition_size: 5
  ba_track_id: "066319231b9d681d7bd32915602c755c"
  disqus_proxy: ""
  disqus_site: ""
  twikoo_env_id: ""
  reward: false
  about_me: true
  omit_categories: false
  page_view_conter: true
  social:
    email: edgarding97@gmail.com
    instagram: https://www.instagram.com/edgarding7/
    github: https://github.com/EdgarDing77
  addtional_menus:
    - title: ARCHIVE
      href: /top/archive/
    - title: ABOUT
      href: /top/about/
  #############
  friends: false
  friend_link:
    - title: oneday oneday 老博客
      href: https://fortuna7.top
  ############
  bookmarks: false
  bookmark_link:
    - title: Martin Fowler
      href: https://martinfowler.com
  ############# 待完善
  algolia_search: true
  algolia_appId: "I62C5GH8Z4"
  algolia_indexName: "edgarding"
  algolia_apiKey: "3c8936237db9c1f21e0936b4f34d3b67"
  algolia:
    vars:
      - title
      - summary
      - date
      - publishdate
      - expirydate
      - permalink
    params:
      - categories
      - tags

outputFormats:
  Algolia:
    baseName: algolia
    isPlainText: true
    mediaType: application/json
    notAlternative: true

markup:
  tableOfContents:
    endLevel: 2
    startLevel: 1
  highlight:
    style: dracula
